apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: server-b
  name: server-b
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-b
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/mend-default: "true"
        io.kompose.service: server-b
    spec:
      containers:
        - image: mend_server-b:latest
          name: server-b
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
      restartPolicy: Always
