apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: server-a
  name: server-a
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-a
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/mend-default: "true"
        io.kompose.service: server-a
    spec:
      containers:
        - image: 160576/mend_server-a:latest
          name: server-a
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always
